---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'Cognito to manage authentication and provide JWT for authorization'

Resources:
    CognitoUserPool:
        Type: 'AWS::Cognito::UserPool'
        Properties:
            UserPoolName: 'UserPool'
            Policies:
                PasswordPolicy:
                    MinimumLength: 8
                    RequireLowercase: true
                    RequireNumbers: true
                    RequireSymbols: true
                    RequireUppercase: true
            UserPoolTags:
                Project: BiteRoll
    CognitoUserPoolClient:
        Type: 'AWS::Cognito::UserPoolClient'
        Properties:
            ClientName: 'UserPoolClient'
            UserPoolId: !Ref CognitoUserPool
            GenerateSecret: false
            ExplicitAuthFlows: 
                - ALLOW_USER_PASSWORD_AUTH
                - ALLOW_REFRESH_TOKEN_AUTH

Outputs:
    CognitoUserPoolID:
        Description: 'ID for the Cognito User Pool'
        Value: !Ref CognitoUserPool
        Export:
            Name: 'CognitoUserPoolID'
    CognitoUserPoolClientId:
        Description: 'ID for the Cognito User Client'
        Value: !Ref CognitoUserPoolClient
        Export:
            Name: 'CognitoUserPoolClient'


