---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'An S3 bucket to hold the static, React driven website'

Resources:
    BiteRollBucket: 
        Type: 'AWS::S3::Bucket'
        Properties: 
            WebsiteConfiguration:
                IndexDocument: index.html
                ErrorDocument: error.html
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true
            BucketName: 'biteroll-static-site-sawyer'
            Tags:
                - Key: Project
                  Value: BiteRoll

Outputs:
    BiteRollBucketDomainName:
        Description: Outputs domain name
        Value: !GetAtt BiteRollBucket.RegionalDomainName
        Export:
            Name: DomainName
    BiteRollBucketName:
        Description: Outputs the buckets name
        Value: !Ref BiteRollBucket
        Export:
            Name: BucketName