---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'Rest API Gateway to handle traffic to lambda backend'

Resources:
    API:
        Type: AWS::ApiGateway::RestApi
        Properties:
            Name: 'RestAPI'

    # /feed
    FeedResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref API
            ParentId: !GetAtt API.RootResourceId
            PathPart: feed
    FeedMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            RestApiId: !Ref API
            ResourceId: !Ref FeedResource
            HttpMethod: GET
            AuthorizationType: NONE
            Integration:
                Type: AWS_PROXY
                IntegrationHttpMethod: POST
                Uri: !Sub
                  - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations'
                  - lambdaArn: !ImportValue LambdaFunctionARN

    # /menu
    MenuResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref API
            ParentId: !GetAtt API.RootResourceId
            PathPart: menu
    MenuMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            RestApiId: !Ref API
            ResourceId: !Ref MenuResource
            HttpMethod: GET
            AuthorizationType: NONE
            Integration:
                Type: AWS_PROXY
                IntegrationHttpMethod: POST
                Uri: !Sub
                  - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations'
                  - lambdaArn: !ImportValue LambdaFunctionARN

    # /like
    LikeResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            RestApiId: !Ref API
            ParentId: !GetAtt API.RootResourceId
            PathPart: like
    LikeMethod:
        Type: AWS::ApiGateway::Method
        Properties:
            RestApiId: !Ref API
            ResourceId: !Ref LikeResource
            HttpMethod: POST
            AuthorizationType: NONE
            Integration:
                Type: AWS_PROXY
                IntegrationHttpMethod: POST
                Uri: !Sub
                  - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations'
                  - lambdaArn: !ImportValue LambdaFunctionARN

    Deployment:
        Type: AWS::ApiGateway::Deployment
        Properties:
            RestApiId: !Ref API
        DependsOn:
          - FeedMethod
          - MenuMethod
          - LikeMethod
    Stage:
        Type: AWS::ApiGateway::Stage
        Properties:
            RestApiId: !Ref API
            DeploymentId: !Ref Deployment
            StageName: dev
    LambdaPermission:
        Type: AWS::Lambda::Permission
        Properties:
            FunctionName: !ImportValue LambdaFunctionARN
            Action: lambda:InvokeFunction
            Principal: apigateway.amazonaws.com
            SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${API}/*'