---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'CloudFront to route to S3 bucket'

Resources:
    BiteRollCloudFront:
        Type: 'AWS::CloudFront::Distribution'
        Properties: 
            DistributionConfig: 
                Comment: "BiteRoll"
                DefaultCacheBehavior: 
                    ViewerProtocolPolicy: 'redirect-to-https'
                    TargetOriginId: 'BiteRollS3Origin'
                    CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  #CachingDisabled
                CacheBehaviors:
                    - CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  #CachingOptimized
                      ViewerProtocolPolicy: 'redirect-to-https'
                      TargetOriginId: 'BiteRollS3Origin'
                      PathPattern: /assets/*
                    - CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
                      ViewerProtocolPolicy: 'redirect-to-https'
                      TargetOriginId: 'BiteRollMediaS3Origin'
                      PathPattern: /media/*
                Enabled: true
                Origins: 
                    - Id: 'BiteRollS3Origin'
                      DomainName: !ImportValue DomainName
                      OriginAccessControlId: !GetAtt BiteRollCloudFrontOAC.Id
                      S3OriginConfig:
                        OriginAccessIdentity: ''
                    - Id: 'BiteRollMediaS3Origin'
                      DomainName: !ImportValue MediaDomainName
                      OriginAccessControlId: !GetAtt BiteRollCloudFrontOAC.Id
                      S3OriginConfig:
                        OriginAccessIdentity: ''                      
                DefaultRootObject: 'index.html'
            Tags:
                - Key: Project
                  Value: BiteRoll
    BiteRollCloudFrontOAC:
        Type: 'AWS::CloudFront::OriginAccessControl'
        Properties:
            OriginAccessControlConfig:
                Name: 'BiteRollCloudFrontOAC'
                OriginAccessControlOriginType: s3
                SigningBehavior: always
                SigningProtocol: sigv4

Outputs:
    CloudFrontDistributionId:
        Description: 'CloudFrontDistro ID used for letting traffic through it into s3'
        Value: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${BiteRollCloudFront}'
        Export:
            Name: CloudFrontDistributionId





