---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'DB to hold restaurant info.'

Resources:
    BiteRollDynamoDBTable:
        Type: AWS::DynamoDB::Table
        Properties: 
            TableName: BiteRollRestaurants
            AttributeDefinitions:
              - AttributeName: placeId
                AttributeType: S
            KeySchema:
              - AttributeName: placeId
                KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            Tags:
              - Key: Project
                Value: BiteRoll

Outputs:
    BiteRollDynamoDBTable:
        Value: !GetAtt BiteRollDynamoDBTable.Arn
        Export:
            Name: DynamoDBARN