---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'DB to hold restaurant info. Deployed as a Global Table with replicas in us-east-2 and us-west-2.'

Resources:
    BiteRollDynamoDBTable:
        Type: AWS::DynamoDB::GlobalTable
        Properties:
            TableName: BiteRollRestaurants
            AttributeDefinitions:
              - AttributeName: placeId
                AttributeType: S
            KeySchema:
              - AttributeName: placeId
                KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            Replicas:
              - Region: us-east-2
                Tags:
                  - Key: Project
                    Value: BiteRoll
              - Region: us-west-2
                Tags:
                  - Key: Project
                    Value: BiteRoll

Outputs:
    BiteRollDynamoDBTable:
        Value: !GetAtt BiteRollDynamoDBTable.Arn
        Export:
            Name: DynamoDBARN