---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'Lambda to handle all backend business logic'

Resources:
    IAMRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument: 
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Principal:
                        Service:
                          - lambda.amazonaws.com
                    Action:
                      - 'sts:AssumeRole'
            Description: "The role of the lambda"
            ManagedPolicyArns: 
              - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    LambdaFunction:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: biteroll-api
            Code:
                ZipFile: |
                    def handler(event, context):
                        return {'statusCode': 200, 'body': 'hello world'}
            Runtime: python3.12   
            Handler: index.handler
            Role: !GetAtt IAMRole.Arn    

Outputs:
    LambdaFunction:
        Description: "Lambda function ARN"
        Value: !GetAtt LambdaFunction.Arn
        Export:
            Name: LambdaFunctionARN
        
