---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'Secrets Manager to store API keys'

Parameters:
    GoogleMapsApiKey:
        Type: String
        NoEcho: true

Resources:
    GoogleMapsSecret:
        Type: AWS::SecretsManager::Secret
        Properties:
            Name: biteroll/google-maps-api-key
            SecretString: !Sub '{"GOOGLE_MAPS_API_KEY": "${GoogleMapsApiKey}"}'
            Tags:
              - Key: Project
                Value: BiteRoll
Outputs:
    GoogleMapsSecret:
        Value: !Ref GoogleMapsSecret
        Export:
            Name: SecretsARN

